apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: frontend
  namespace: argocd
spec:
  destination:
    namespace: dev
    name: in-cluster
  project: default
  sources:
    - repoURL: 'https://github.com/phamidko/eks-argocd.git'
      path: frontend
      targetRevision: 'master'
      ref: values

    - repoURL: 'registry-1.docker.io/phamiducla'
      path: 'optum-frontend'
      targetRevision: 0.1.0
      chart: optum-frontend
      helm:
          valueFiles:
            - $values/frontend/frontend-values.yaml
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        maxDuration: 3m0s
        factor: 2